const niches = [
    "Twitter",
    "Growth Hacking",
    "Newsletter Tool",
    "Movie",
    "Helpdesk",
    "Shopify",
    "Image Tool",
    "Image Generation",
    "Color",
    "Collaboration Tool",
    "Icon",
    "Logo",
    "URL",
    "Font",
    "Video Tool",
    "Traffic Analysis",
    "Auditing Tool",
    "Scheduling Tool",
    "Survey",
    "AB Testing",
    "Study Tool",
    "Inspiration & Guide",
    "Invoice",
    "Digital Nomad",
    "API Integration",
    "Facebook",
    "Reporting Tool",
    "News",
    "Notion",
    "Airtable",
    "Music",
    "Blogging",
    "Remote Meeting",
    "Slack",
    "HR Tool",
    "Voice Tool",
    "Sales Tool",
    "PDF Tool",
    "HTML Tool",
    "Spreadsheet",
    "ChatGPT",
    "File namagement",
    "RSS Feed",
    "Discord",
    "JSON Tool",
    "CSV Tool",
    "Knowledge Base",
    "WordPress",
    "Whatsapp",
    "Hiring",
    "Note Taking",
    "Team Management",
    "OKR",
    "KPI",
    "Excel",
    "Webhook",
    "Proxy",
    "Salesforce",
    "Presentation",
    "SQL",
    "Idea Management",
    "API",
    "Programming Tool",
    "Wireframe & Prototype",
    "Keyword Research",
    "Linux",
    "PostgreSQL",
    "Copywriting",
    "Reddit",
    "Cold Outreach",
    "OpenAI",
    "GPT-3",
    "CSS & Web design",
    "Figma",
    "Hedge Fund",
    "Mutual Fund",
    "Mortgage Tool",
    "WooCommerce",
    "Form Builder",
    "Language Tool",
    "CI CD",
    "UI",
    "Interview Tool",
    "Real Estate",
    "Payscale",
    "LinkedIn",
    "Prompt Tool",
    "Advertisement",
    "Review Tool",
    "Marketplace",
    "Coupon & Deal",
    "Guide & Information",
    "ecommerce",
    "Recommendation Engine",
    "Inspection Tool",
    "Forecast Tool",
    "Community Management",
    "Productivity",
    "Directory Database",
    "Investor & VC",
    "Feedback Management",
    "Privacy Management",
    "Time & Timer",
    "Meal Planning",
    "Project Management",
    "Property",
    "personal Finance Tool",
    "Integration Tool",
    "Freelancing",
    "Hosting Platform",
    "Gaming",
    "Testing",
    "Monitoring Tool",
    "Affiliate Marketing",
    "Competitor Research",
    "Fundraising",
    "Influencer Markteing",
    "YouTube",
    "Typography",
    "Workflow Automation",
    "Accounting",
    "Email",
    "Gmail",
    "Email Marketing",
    "Resume",
    "Performance Management",
    "Job",
    "Payroll",
    "Content Writing",
    "Portfolio Management",
    "Trading",
    "Cryptocurrency",
    "Credit Card",
    "Stock Market",
    "Analytics",
    "Lifestyle",
    "No Code",
    "Landing Page",
    "Website Builder",
    "Git & Github",
    "Ticketing Tool",
    "Membership Management",
    "Journalist",
    "Reputation Management",
    "Visualization Tool",
    "Tax",
    "Cloud",
    "Calculator",
    "Inventory Management"
]
module.exports = niches